### ISSUE TITLE
Zst compression for control + data

### ISSUE THREAD

**Issue by VISTALL** [artipie/debian-adapter#130]
Hello. I created a deb file in Ubuntu 22 (WSL, Win10). 

```
Debian 'dpkg-deb' package archive backend version 1.21.1 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
```

Dpkg util create a deb file using Zst compression. For now it's impossible read this package type.

Result attached.

[test_3.0_1_amd64.deb.zip](https://github.com/artipie/debian-adapter/files/11637994/test_3.0_1_amd64.deb.zip)

Exception
```
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unsupported archive type
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.reactivex.internal.operators.flowable.FlowableFromFuture.subscribeActual(FlowableFromFuture.java:42)
	... 19 more
Caused by: java.lang.IllegalStateException: Unsupported archive type
	at com.artipie.debian.metadata.Control$FromInputStream.stream(Control.java:110)
	at com.artipie.debian.metadata.Control$FromInputStream.asString(Control.java:79)
	at com.artipie.debian.Debian$Asto.lambda$updatePackages$0(Debian.java:104)
	at com.artipie.asto.streams.ContentAsStream.lambda$process$1(ContentAsStream.java:56)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	... 5 more
```

**Comment by VISTALL** [comment]
Thanks 👍🏻

**Comment by olenagerasimova** [comment]
@VISTALL please, note, that new artipie version with this fix is not yes released. I'll release it tomorrow and let you know
